version: "2.1"

services:
    nginx:
        build: ./nginx/
        ports:
            - 8000:80
        volumes:
            - "${PROJECT_ROOT}/${PROJECT_DIRECTORY}:/var/www/html:ro"
            - "${PROJECT_ROOT}/${LOG_DIRECTORY}:/var/log/nginx/"
        networks:
            - server
        depends_on:
            - php

    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - "${PROJECT_ROOT}/${PROJECT_DIRECTORY}:/var/www/html"
            - "${SSH_KEY_ROOT}:/root/.ssh"
        networks:
            - database
            - server
        depends_on:
            - mysql

    mysql:
        image: mysql:latest
        volumes:
            - "${PROJECT_ROOT}/${DATABASE_DIRECTORY}:/var/lib/mysql"
        ports:
            - 4567:3306
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        networks:
            - database
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql

volumes:
    data:

networks:
    database:
    server:
