version: "2.1"

services:
    nginx:
        build: ./nginx/
        container_name: ${PROJECT_NAME}_nginx
        dns_search: nginx
        ports:
            - 80:80
        volumes:
            - "~/${PROJECT_NAME}/src:/var/www/html:ro"
            - "~/${PROJECT_NAME}/logs:/var/log/nginx/"
        networks:
            - server
        depends_on:
            - php

    php:
        build: ./php/
        container_name: ${PROJECT_NAME}_php
        expose:
            - 9000
        volumes:
            - "~/${PROJECT_NAME}/src:/var/www/html"
            - "${SSH_KEY_ROOT}:/root/.ssh"
        working_dir: /var/www/html
        dns_search: php
        networks:
            - database
            - server
        depends_on:
            - mysql

    mysql:
        build: ./mysql/
        container_name: ${PROJECT_NAME}_mysql
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - database
        dns_search: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        command: mysqld --sql_mode='' --max_allowed_packet=512M --innodb_buffer_pool_size=512M --innodb_flush_log_at_trx_commit=0
        restart: always

    phpmyadmin:
        build: ./phpmyadmin/
        container_name: ${PROJECT_NAME}_phpmyadmin
        ports:
            - 8080:80
        networks:
            - database
        depends_on:
            - mysql
        dns_search: phpmyadmin
        environment:
            PMA_HOST: mysql

volumes:
    db-data:
      driver: local

networks:
    database:
    server:
